# Site
name: '彭钊的博客'
description: '满满的世界里，我想懂得更多.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: '彭钊的网页'
email: '270316095@qq.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    sal:
      name:           blankpeng
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar1.jpg
      bio:            "你好，博客的作者!"
      email:          wowthemesnet@gmail.com
      qq:             270316095

    jane:
      name:           other
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "尚需要人们的参与!"
      email:          fakemail@gmail.com
      qq:             xxxxxx

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
